id: P007896
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:47:52.008722
source_metadata:
  id: bdr:W24589
  title: དེབ་ཆུང་ཨ་རུ་རའི་དགའ་ཚལ
  author: ''
  volumes:
    78180d0a7bcf4820b4ca3e5274bfa223:
      image_group_id: I1PD28135
      title: Volume 1 of deb chung a ru ra'i dga' tshal
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
