id: P007896
initial_creation_type: ocr
source_metadata:
  id: bdr:W24589
  title: དེབ་ཆུང་ཨ་རུ་རའི་དགའ་ཚལ
  author: ''
  volumes:
    9540e0cee4e3493f8f591c5466b9a0ec:
      image_group_id: I1PD28135
      title: ''
      volume_number: 1
      total_pages: 364
ebook_metadata:
  title: དེབ་ཆུང་ཨ་རུ་རའི་དགའ་ཚལ
  author: ''
  sku: P007896
  cover: cover.jpg
  layers:
  - pagination
