id: IB9BB2389
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:50:08+00:00'
last_modified: '2022-06-09T07:11:41.361497+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24589
  title: དེབ་ཆུང་ཨ་རུ་རའི་དགའ་ཚལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B84E:
      image_group_id: I1PD28135
      title: Volume 1 of deb chung a ru ra'i dga' tshal
      total_pages: 364
      order: 1
      base_file: B84E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
